### ISSUE TITLE
Problem at Transition from FlowLayout to BlazeLayout

### ISSUE THREAD

**Issue by emminnn** [kadirahq/flow-router#365]
Hi there!

I pursue the transition from FlowLayout to BlazeLayout as part of the transition from <b>Flow Router I</b> to <b>Flow Router II</b>. I tried to do all that was noted <a href="https://github.com/kadirahq/flow-router#migrating-into-20">here</a>. Then I get this error on my console, without the ability to start the app.

<code>W20151024-07:37:57.782(2)? (STDERR) TypeError: Cannot read property 'BlazeLayout' of undefined
W20151024-07:37:57.782(2)? (STDERR)     at packages/global-imports.js:11:45
W20151024-07:37:57.782(2)? (STDERR)     at /Users/emindurak/Desktop/deneme1/kitapp/.meteor/local/build/programs/server/boot.js:222:10
W20151024-07:37:57.783(2)? (STDERR)     at Array.forEach (native)
W20151024-07:37:57.783(2)? (STDERR)     at Function._.each._.forEach (/Users/emindurak/.meteor/packages/meteor-tool/.1.1.4.hbupt5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151024-07:37:57.783(2)? (STDERR)     at /Users/emindurak/Desktop/deneme1/kitapp/.meteor/local/build/programs/server/boot.js:117:5
</code>

Any help will be appreciated to resolve the issue. Thanks!

**Comment by emminnn** [comment]
OK, now I updated everything on my app including Meteor core to 1.2. The problem regarding BlazeLayout seems to disappear, but I have another problem that seems occur due to the SearchSource package I use:

<code>W20151024-08:06:18.655(2)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20151024-08:06:18.655(2)? (STDERR)     at Package (packages/meteorhacks_search-source/packages/meteorhacks_search-source.js:17:1)
W20151024-08:06:18.655(2)? (STDERR)     at Package (packages/meteorhacks_search-source/packages/meteorhacks_search-source.js:80:1)
W20151024-08:06:18.655(2)? (STDERR)     at /Users/emindurak/Desktop/deneme1/kitapp/.meteor/local/build/programs/server/packages/meteorhacks_search-source.js:101:4
W20151024-08:06:18.655(2)? (STDERR)     at /Users/emindurak/Desktop/deneme1/kitapp/.meteor/local/build/programs/server/packages/meteorhacks_search-source.js:110:3
W20151024-08:06:18.655(2)? (STDERR)     at /Users/emindurak/Desktop/deneme1/kitapp/.meteor/local/build/programs/server/boot.js:242:10
W20151024-08:06:18.656(2)? (STDERR)     at Array.forEach (native)
W20151024-08:06:18.656(2)? (STDERR)     at Function._.each._.forEach (/Users/emindurak/.meteor/packages/meteor-tool/.1.1.9.3zwwyi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151024-08:06:18.656(2)? (STDERR)     at /Users/emindurak/Desktop/deneme1/kitapp/.meteor/local/build/programs/server/boot.js:137:5</code>

Still can't run the app :/

**Comment by emminnn** [comment]
I uninstalled and reinstalled the Search Source package, and it started working fine.
