### ISSUE TITLE
"Meteor code must always run within a Fiber." when using ssr

### ISSUE THREAD

**Issue by kctang** [kadirahq/flow-router#522]
I am trying to get a very simple app running based on Mantra. Got this error:

    E20160206-19:47:20.502(8) (webapp_server.js:716) Error running template: Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
      at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Tracker.autorun (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:51:29)
    at [object Object].Blaze.View.autorun (packages/blaze/view.js:209:1)
    at [object Object].<anonymous> (packages/blaze/builtins.js:157:1)
    at fireCallbacks (packages/blaze/view.js:279:1)
    at Object.Tracker.nonreactive (packages/tracker/tracker.js:589:1)
    at packages/blaze/view.js:276:1
    at Object.Blaze._withCurrentView (packages/blaze/view.js:538:1)
    at Object.Blaze._fireCallbacks (packages/blaze/view.js:275:1)

Replacing flow-router-ssr with flow-router solved the problem - i'm now able to get a very simple react component displayed on screen. However, the mantra sample blog seems to be using flow-router-ssr.

Is this an ssr bug? What's the right way of doing this? Also, any slack/gitter for mantra?

Running 1.3 beta8.

**Comment by timothyarmes** [comment]
Same problem here.

**Comment by novium** [comment]
This should be fixed in the next Meteor beta 
Issue: https://github.com/meteor/meteor/issues/6170
PR: https://github.com/meteor/meteor/pull/6179
Try downgrading to 1.3-modules-beta.6

**Comment by arunoda** [comment]
Is there a beta9 ?

**Comment by onedr0p** [comment]
Looks like this is fixed in Meteor Beta.11

**Comment by novium** [comment]
Can confirm that it works 1.3-beta.11

**Comment by arunoda** [comment]
Yep. Here's a sample app too: https://github.com/kadira-samples/meteor-data-and-react
