### ISSUE TITLE
Error when doing SSR. path:/: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by SachaG** [kadirahq/flow-router#578]
I've been trying to deploy [Nova](https://github.com/TelescopeJS/Telescope/tree/nova) to Galaxy, and although I can load the site, SSR is not enabled (at least judging from the source of the page) and I'm getting this error over and over in the logs:

```
2016-03-30 14:59:55+09:00TypeError: Cannot read property '_currentElement' of null
deh3
2016-03-30 14:59:55+09:00 at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/app/bundle/programs/server/npm/node_modules/react/lib/ReactCompositeComponent.js:559:52)
deh3
2016-03-30 14:59:55+09:00 at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/app/bundle/programs/server/npm/node_modules/react/lib/ReactCompositeComponent.js:544:10)
deh3
2016-03-30 14:59:55+09:00 at [object Object].ReactCompositeComponentMixin.updateComponent (/app/bundle/programs/server/npm/node_modules/react/lib/ReactCompositeComponent.js:473:12)
deh3
2016-03-30 14:59:55+09:00 at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/app/bundle/programs/server/npm/node_modules/react/lib/ReactCompositeComponent.js:421:12)
deh3
2016-03-30 14:59:55+09:00 at Object.ReactReconciler.performUpdateIfNecessary (/app/bundle/programs/server/npm/node_modules/react/lib/ReactReconciler.js:102:22)
deh3
2016-03-30 14:59:55+09:00 at runBatchedUpdates (/app/bundle/programs/server/npm/node_modules/react/lib/ReactUpdates.js:129:21)
deh3
2016-03-30 14:59:55+09:00 at ReactReconcileTransaction.Mixin.perform (/app/bundle/programs/server/npm/node_modules/react/lib/Transaction.js:136:20)
deh3
2016-03-30 14:59:55+09:00 at ReactUpdatesFlushTransaction.Mixin.perform (/app/bundle/programs/server/npm/node_modules/react/lib/Transaction.js:136:20)
deh3
2016-03-30 14:59:55+09:00 at ReactUpdatesFlushTransaction.assign.perform (/app/bundle/programs/server/npm/node_modules/react/lib/ReactUpdates.js:86:38)
deh3
2016-03-30 14:59:55+09:00 at Object.flushBatchedUpdates (/app/bundle/programs/server/npm/node_modules/react/lib/ReactUpdates.js:147:19)
```

Any idea what could be causing it? I should add that the app works fine when I run it locally with the same `MONGO_URL`.

**Comment by SachaG** [comment]
Oh also the db is hosted for free on MongoLab, so it's not very fast. Could SSR be timing out maybe?

**Comment by richpowell** [comment]
Im getting this error also..  No luck figuring it out. @SachaG did you galaxy with any other mongo service and get it to work ?

**Comment by SachaG** [comment]
I ended up getting this error locally as well so it's not related to Galaxy after all. Doesn't seem to affect the app too much though. 

Also I haven't been able to run my app on Galaxy because of a memory leak, but I don't know if it's related or not.
