### ISSUE TITLE
Error when doing SSR. path: /: FlowRouter SSR is required to mount components in the server.

### ISSUE THREAD

**Issue by simsim0709** [kadirahq/flow-router#695]
Hi,

I am building app with mantra spec + FlowRouterSSR.
I got this error and I can't figure it out.
I changed "client" folder name to "app" anyway. 

```
W20161027-16:18:13.983(9)? (STDERR) Error when doing SSR. path:/: FlowRouter SSR is required to mount components in the server.
W20161027-16:18:13.997(9)? (STDERR) Error: FlowRouter SSR is required to mount components in the server.
W20161027-16:18:13.997(9)? (STDERR)     at mounter (/Users/similkwon/dev/voyage/hubc-react/node_modules/react-mounter/dist/server.js:37:11)
W20161027-16:18:13.997(9)? (STDERR)     at mount (/Users/similkwon/dev/voyage/hubc-react/node_modules/react-mounter/dist/index.js:29:3)
W20161027-16:18:13.997(9)? (STDERR)     at Object.action (app/modules/core/routes.jsx:28:7)
W20161027-16:18:13.998(9)? (STDERR)     at packages/thelohoadmin:flow-router-ssr/server/route.js:85:41
W20161027-16:18:13.998(9)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20161027-16:18:13.998(9)? (STDERR)     at packages/thelohoadmin:flow-router-ssr/server/route.js:70:33
W20161027-16:18:13.998(9)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20161027-16:18:13.998(9)? (STDERR)     at Route._processFromSsr (packages/thelohoadmin:flow-router-ssr/server/route.js:69:29)
W20161027-16:18:13.999(9)? (STDERR)     at packages/meteorhacks_fast-render.js:259:21
W20161027-16:18:13.999(9)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
```

**Comment by alexismoreau** [comment]
I run into the same error, did you find out the workaround ?
